package com.termmed.util;

public class Constants {
    public static final String ANCESTOR_METADATA_JSON="{\"options\":{},\"indexes\":[{\"v\":2,\"key\":{\"_id\":1},\"name\":\"_id_\",\"ns\":\"===DB===.===COLL===ancestor===PATH===\"},{\"v\":2,\"key\":{\"c\":1},\"name\":\"c_1\",\"ns\":\"===DB===.===COLL===ancestor===PATH===\"}],\"uuid\":\"9708d0b94c5d43389c25edccad26e9dc\"}";
    public static final String DESCENDANT_METADATA_JSON="{\"options\":{},\"indexes\":[{\"v\":2,\"key\":{\"_id\":1},\"name\":\"_id_\",\"ns\":\"===DB===.===COLL===descendant===PATH===\"},{\"v\":2,\"key\":{\"c\":1},\"name\":\"c_1\",\"ns\":\"===DB===.===COLL===descendant===PATH===\"}],\"uuid\":\"8ebf613afa654c909012b530e31c2801\"}";
    public static final String STATED_ANCESTOR_METADATA_JSON="{\"options\":{},\"indexes\":[{\"v\":2,\"key\":{\"_id\":1},\"name\":\"_id_\",\"ns\":\"===DB===.===COLL===stancestor===PATH===\"},{\"v\":2,\"key\":{\"c\":1},\"name\":\"c_1\",\"ns\":\"===DB===.===COLL===stancestor===PATH===\"}],\"uuid\":\"9708d0b94c5d43389c25edccad26e9dd\"}";
    public static final String STATED_DESCENDANT_METADATA_JSON="{\"options\":{},\"indexes\":[{\"v\":2,\"key\":{\"_id\":1},\"name\":\"_id_\",\"ns\":\"===DB===.===COLL===stdescendant===PATH===\"},{\"v\":2,\"key\":{\"c\":1},\"name\":\"c_1\",\"ns\":\"===DB===.===COLL===stdescendant===PATH===\"}],\"uuid\":\"8ebf613afa654c909012b530e31c2802\"}";

    public static final String REFSET_METADATA_JSON="{\"options\":{},\"indexes\":[{\"v\":2,\"key\":{\"_id\":1},\"name\":\"_id_\",\"ns\":\"===DB===.===COLL===refsets===PATH===\"},{\"v\":2,\"key\":{\"c\":1},\"name\":\"c_1\",\"ns\":\"===DB===.===COLL===refsets===PATH===\"}],\"uuid\":\"bbe7400e8f4d4515a0c83eef7870cde4\"}";
    public static final String DEFINITION_METADATA_JSON="{\"options\":{},\"indexes\":[{\"v\":2,\"key\":{\"_id\":1},\"name\":\"_id_\",\"ns\":\"===DB===.===COLL===definition===PATH===\"},{\"v\":2,\"key\":{\"c\":1},\"name\":\"c_1\",\"ns\":\"===DB===.===COLL===definition===PATH===\"},{\"v\":2,\"key\":{\"g.rg.t\":1,\"g.rg.d\":1},\"name\":\"g.rg.t_1_g.rg.d_1\",\"ns\":\"===DB===.===COLL===definition===PATH===\"},{\"v\":2,\"key\":{\"m\":1},\"name\":\"m_1\",\"ns\":\"===DB===.===COLL===definition===PATH===\"},{\"v\":2,\"key\":{\"st\":1},\"name\":\"st_1\",\"ns\":\"===DB===.===COLL===definition===PATH===\"},{\"v\":2,\"key\":{\"p\":1},\"name\":\"p_1\",\"ns\":\"===DB===.===COLL===definition===PATH===\"}],\"uuid\":\"d57966ceb7c847328f7afe3013cd478d\"}";
    public static final String STATED_DEFINITION_METADATA_JSON="{\"options\":{},\"indexes\":[{\"v\":2,\"key\":{\"_id\":1},\"name\":\"_id_\",\"ns\":\"===DB===.===COLL===stdefinition===PATH===\"},{\"v\":2,\"key\":{\"c\":1},\"name\":\"c_1\",\"ns\":\"===DB===.===COLL===stdefinition===PATH===\"},{\"v\":2,\"key\":{\"g.rg.t\":1,\"g.rg.d\":1},\"name\":\"g.rg.t_1_g.rg.d_1\",\"ns\":\"===DB===.===COLL===stdefinition===PATH===\"},{\"v\":2,\"key\":{\"m\":1},\"name\":\"m_1\",\"ns\":\"===DB===.===COLL===stdefinition===PATH===\"},{\"v\":2,\"key\":{\"st\":1},\"name\":\"st_1\",\"ns\":\"===DB===.===COLL===stdefinition===PATH===\"},{\"v\":2,\"key\":{\"p\":1},\"name\":\"p_1\",\"ns\":\"===DB===.===COLL===stdefinition===PATH===\"}],\"uuid\":\"d57966ceb7c847328f7afe3013cd478e\"}";
    public static final String AXIOM_REFSET = "733073007";
    public static final Long PREFERRED_ACCEPTABILITY = 900000000000548007L;
    public static final String SYNONYM_TYPE = "900000000000013009";
}
